//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsumeWebservice2.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CartServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CartService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddToCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveFromCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCartItemsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CartService() {
            this.Url = global::ConsumeWebservice2.Properties.Settings.Default.ConsumeWebservice2_localhost_CartService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddToCartCompletedEventHandler AddToCartCompleted;
        
        /// <remarks/>
        public event RemoveFromCartCompletedEventHandler RemoveFromCartCompleted;
        
        /// <remarks/>
        public event GetCartItemsCompletedEventHandler GetCartItemsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddToCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddToCart(string itemId, int quantity) {
            this.Invoke("AddToCart", new object[] {
                        itemId,
                        quantity});
        }
        
        /// <remarks/>
        public void AddToCartAsync(string itemId, int quantity) {
            this.AddToCartAsync(itemId, quantity, null);
        }
        
        /// <remarks/>
        public void AddToCartAsync(string itemId, int quantity, object userState) {
            if ((this.AddToCartOperationCompleted == null)) {
                this.AddToCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddToCartOperationCompleted);
            }
            this.InvokeAsync("AddToCart", new object[] {
                        itemId,
                        quantity}, this.AddToCartOperationCompleted, userState);
        }
        
        private void OnAddToCartOperationCompleted(object arg) {
            if ((this.AddToCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddToCartCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveFromCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveFromCart(string itemId) {
            this.Invoke("RemoveFromCart", new object[] {
                        itemId});
        }
        
        /// <remarks/>
        public void RemoveFromCartAsync(string itemId) {
            this.RemoveFromCartAsync(itemId, null);
        }
        
        /// <remarks/>
        public void RemoveFromCartAsync(string itemId, object userState) {
            if ((this.RemoveFromCartOperationCompleted == null)) {
                this.RemoveFromCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveFromCartOperationCompleted);
            }
            this.InvokeAsync("RemoveFromCart", new object[] {
                        itemId}, this.RemoveFromCartOperationCompleted, userState);
        }
        
        private void OnRemoveFromCartOperationCompleted(object arg) {
            if ((this.RemoveFromCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveFromCartCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCartItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CartItem[] GetCartItems() {
            object[] results = this.Invoke("GetCartItems", new object[0]);
            return ((CartItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCartItemsAsync() {
            this.GetCartItemsAsync(null);
        }
        
        /// <remarks/>
        public void GetCartItemsAsync(object userState) {
            if ((this.GetCartItemsOperationCompleted == null)) {
                this.GetCartItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCartItemsOperationCompleted);
            }
            this.InvokeAsync("GetCartItems", new object[0], this.GetCartItemsOperationCompleted, userState);
        }
        
        private void OnGetCartItemsOperationCompleted(object arg) {
            if ((this.GetCartItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCartItemsCompleted(this, new GetCartItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CartItem {
        
        private string itemIdField;
        
        private string itemNameField;
        
        private decimal priceField;
        
        private int quantityField;
        
        /// <remarks/>
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AddToCartCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RemoveFromCartCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCartItemsCompletedEventHandler(object sender, GetCartItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCartItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCartItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CartItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CartItem[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591